---
public_protocol: https
private_protocol: http
domain_name: "{{ subdomain }}.{{ hosted_zone }}"
auth_public_url: "{{ public_protocol }}://{{ domain_name }}/auth"
oauth_domain_name: "oauth-{{ domain_name }}"
oauth_public_url: "{{ public_protocol }}://{{ oauth_domain_name }}"
oauth_rp_url: "{{ public_protocol }}://123done-{{ subdomain }}.{{ hosted_zone }}"
content_public_url: "{{ public_protocol }}://{{ domain_name }}"
content_public_port: 80
content_private_port: 3030
content_git_repo: https://github.com/shane-tomlinson/fxa-content-server.git
content_git_version: issue-1386-add-iframe-channel
